// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package jobdb

import (
	"time"
)

type Job struct {
	ID        string
	Type      string
	ArgsData  []byte
	Status    string
	Result    string
	Priority  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
