// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package jobdb

import (
	"context"
	"database/sql"
	"time"
)

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ArgsData,
		&i.Status,
		&i.Result,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingJobs = `-- name: GetPendingJobs :many
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
WHERE status = 'PENDING'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, getPendingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ArgsData,
			&i.Status,
			&i.Result,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (id, type, args_data, status, result, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertJobParams struct {
	ID        string
	Type      string
	ArgsData  []byte
	Status    string
	Result    string
	Priority  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.Type,
		arg.ArgsData,
		arg.Status,
		arg.Result,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAllJobs = `-- name: ListAllJobs :many
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
ORDER BY created_at ASC
LIMIT CASE WHEN ? = 0 THEN -1 ELSE ? END
OFFSET ?
`

type ListAllJobsParams struct {
	Column1 interface{}
	Column2 interface{}
	Offset  int64
}

func (q *Queries) ListAllJobs(ctx context.Context, arg ListAllJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listAllJobs, arg.Column1, arg.Column2, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ArgsData,
			&i.Status,
			&i.Result,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
WHERE status = ?
ORDER BY created_at ASC
LIMIT CASE WHEN ? = 0 THEN -1 ELSE ? END
OFFSET ?
`

type ListJobsByStatusParams struct {
	Status  string
	Column2 interface{}
	Column3 interface{}
	Offset  int64
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatus,
		arg.Status,
		arg.Column2,
		arg.Column3,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ArgsData,
			&i.Status,
			&i.Result,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatusAndType = `-- name: ListJobsByStatusAndType :many
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
WHERE status = ? AND type = ?
ORDER BY created_at ASC
LIMIT CASE WHEN ? = 0 THEN -1 ELSE ? END
OFFSET ?
`

type ListJobsByStatusAndTypeParams struct {
	Status  string
	Type    string
	Column3 interface{}
	Column4 interface{}
	Offset  int64
}

func (q *Queries) ListJobsByStatusAndType(ctx context.Context, arg ListJobsByStatusAndTypeParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByStatusAndType,
		arg.Status,
		arg.Type,
		arg.Column3,
		arg.Column4,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ArgsData,
			&i.Status,
			&i.Result,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByType = `-- name: ListJobsByType :many
SELECT id, type, args_data, status, result, priority, created_at, updated_at
FROM jobs
WHERE type = ?
ORDER BY created_at ASC
LIMIT CASE WHEN ? = 0 THEN -1 ELSE ? END
OFFSET ?
`

type ListJobsByTypeParams struct {
	Type    string
	Column2 interface{}
	Column3 interface{}
	Offset  int64
}

func (q *Queries) ListJobsByType(ctx context.Context, arg ListJobsByTypeParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByType,
		arg.Type,
		arg.Column2,
		arg.Column3,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ArgsData,
			&i.Status,
			&i.Result,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :execresult
UPDATE jobs
SET status = ?, result = ?, updated_at = ?
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status    string
	Result    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.Result,
		arg.UpdatedAt,
		arg.ID,
	)
}

const upsertJob = `-- name: UpsertJob :exec
INSERT OR REPLACE INTO jobs (id, type, args_data, status, result, priority, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type UpsertJobParams struct {
	ID        string
	Type      string
	ArgsData  []byte
	Status    string
	Result    string
	Priority  int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertJob,
		arg.ID,
		arg.Type,
		arg.ArgsData,
		arg.Status,
		arg.Result,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
